=== cptpiepmatz/pretty-ts-imports/config.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "Record<string,string>": {
            "type": "object"
        },
        "default_1": {
            "description": "Interface describing how the outputted imports should be formatted.",
            "properties": {
                "bracketIndent": {
                    "description": "The indent at the start and end of the named imports.",
                    "type": "number"
                },
                "indent": {
                    "description": "The indent if the import needs to use line break in order to fit.",
                    "type": "number"
                },
                "maxColumns": {
                    "description": "The max columns the output should not overlap.",
                    "type": "number"
                },
                "quoteStyle": {
                    "description": "The quote style to use for the import source.",
                    "enum": [
                        "double",
                        "single"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        }
    },
    "description": "Interface describing how configs should look.\n\nUsed by{@linkConfigHandler}.",
    "properties": {
        "formatting": {
            "$ref": "#/definitions/default_1",
            "description": "Formatting options."
        },
        "require": {
            "$ref": "#/definitions/Record<string,string>",
            "description": "An object containing custom compare functions.\nUse the key for the function name and the value for the path of compare\nfunction relative to the config file.\n\nTo make sure the functions do work correctly, they should implement either{@linkImportCompareFunction},{@linkImportElementCompareFunction}or{@linkSeparateByFunction}and export their function as default."
        },
        "separateBy": {
            "description": "Names of group by functions to determine where to put a separator line.\nOnly one line around every group is possible, therefore the order is not\nimportant.\n\n<b>Note: the names need to be exact with the function names.</b>",
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "sortImportElements": {
            "description": "Names of the compare functions in every import in order of execution.\nPrimp will run through these to sort all import elements.\n\n<b>Note: the names need to be exact with the function names.</b>",
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "sortImports": {
            "description": "Names of the compare functions in order of execution.\nPrimp will run through these to sort all imports.\n\n<b>Note: The names need to be exact with function names.</b>",
            "items": {
                "type": "string"
            },
            "type": "array"
        }
    },
    "type": "object"
}

=== cptpiepmatz/pretty-ts-imports/examples/configs/primp.json
{
  "sortImports": [
    "!sideEffect",
    "sourceType",
    "dotJSFirst",
    "!namespacePresence",
    "pathName",
    "sourceName"
  ],
  "sortImportElements": [
    "elementType",
    "basenameGroup",
    "elementName"
  ],
  "separateBy": [
    "unequalSideEffectUse",
    "unequalPackageState",
    "unequalNamespaceUse"
  ],
  "formatting": {
    "indent": 2,
    "bracketIndent": 0,
    "quoteStyle": "double",
    "maxColumns": 80
  },
  "require": {
    "dotJSFirst": "../compare_functions/imports/dotJSFirst.ts"
  }
}
